name: CI
on: [push, pull_request]
    branches: [ master, develop ]

jobs:
  test_Pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build:dll
      - run: yarn build
